[package]
name = "mcp"
version = "0.1.0"
authors = ["Yushi Omote <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
specs = "0.15"
specs-derive = "0.4"
quicksilver = "0.3"
derive-new = "0.5"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
