enemy_large:
  - aid: enemy_l1
    time: 10
  - aid: enemy_l2
    time: 10
enemy_medium:
  - aid: enemy_m1
    time: 5
  - aid: enemy_m2
    time: 5
enemy_small:
  - aid: enemy_s1
    time: 10
  - aid: enemy_s2
    time: 10
bullet:
  - aid: shot_b1
    time: 10
  - aid: shot_b2
    time: 10
boss:
  - aid: boss
    time: 1
ship:
  - aid: ship1
    time: 10
  - aid: ship2
    time: 10
item:
  - aid: power_a1
    time: 10
  - aid: power_a2
    time: 10
