enemy1: # Heavy
  life: 100
  size: [26.0, 30.0]
  animation: enemy_large
  features:
    - name: linear_move
      vel: [0.0, 0.8]
    - name: radial_attack
      damage: 10
      frequency: 200
      size: [10.0, 10.0]
      vel: 2.0
      range: 1.57
      num: 7
      animation: bullet
enemy2: # Speedy
  life: 20
  size: [32.0, 16.0]
  animation: enemy_medium
  features:
    - name: linear_move
      vel: [0.0, 2.0]
    - name: radial_attack
      damage: 10
      frequency: 100
      size: [10.0, 10.0]
      vel: 8.0
      animation: bullet
enemy3: # Small
  life: 3
  size: [16.0, 16.0]
  animation: enemy_small
  features:
    - name: linear_move
      vel: [0.0, 0.8]
    - name: radial_attack
      damage: 10
      frequency: 100
      size: [8.0, 8.0]
      vel: 2.0
      animation: bullet
boss1:
  life: 2000
  size: [100.0, 100.0]
  animation: boss
  features:
    - name: linear_move
      vel: [0.0, 0.2]
    - name: wave_move
      width: 2.0
      freq: 300
    - name: radial_attack
      damage: 20
      frequency: 100
      size: [12.0, 12.0]
      vel: 2.0
      range: 6.28
      num: 24
      animation: bullet
