player:
  size: [16.0, 24.0]
  animation: ship
  components:
    - name: player
      life: 150
      level: 0
    - name: bound
      area: [0.0, 0.0, 800.0, 600.0]
    - name: control
      vel: 3.0
    - name: shooter
    - name: mustlive
item:
  size: [20.0, 20.0]
  animation: item
  components:
    - name: item
      id: 1
    - name: linear_move
      vel: [0.0, 0.6]
enemy1: # Heavy
  size: [26.0, 30.0]
  animation: enemy_large
  components:
    - name: enemy
      life: 100
    - name: linear_move
      vel: [0.0, 0.8]
    - name: radial_attack
      damage: 10
      frequency: 200
      size: [10.0, 10.0]
      vel: 2.0
      range: 1.57
      num: 7
      animation: bullet
enemy2: # Speedy
  size: [32.0, 16.0]
  animation: enemy_medium
  components:
    - name: enemy
      life: 20
    - name: linear_move
      vel: [0.0, 2.0]
    - name: radial_attack
      damage: 10
      frequency: 100
      size: [10.0, 10.0]
      vel: 8.0
      animation: bullet
enemy3: # Small
  size: [16.0, 16.0]
  animation: enemy_small
  components:
    - name: enemy
      life: 3
    - name: linear_move
      vel: [0.0, 0.8]
    - name: radial_attack
      damage: 10
      frequency: 100
      size: [8.0, 8.0]
      vel: 2.0
      animation: bullet
boss1:
  size: [100.0, 100.0]
  animation: boss
  components:
    - name: enemy
      life: 2000
    - name: linear_move
      vel: [0.0, 0.2]
    - name: wave_move
      width: 2.0
      freq: 300
    - name: radial_attack
      damage: 20
      frequency: 100
      size: [12.0, 12.0]
      vel: 2.0
      range: 6.28
      num: 24
      animation: bullet
    - name: bound
      area: [0.0, 0.0, 800.0, 300.0]
