enemy1:
  life: 100
  size: [26.0, 30.0]
  animation:
    - aid: 2
      time: 10
    - aid: 10002
      time: 10
  motion:
    - name: constant
      vel: [0.0, 100.0]
  attack:
    - name: single
      damage: 10
      frequency: 200
      size: [10.0, 10.0]
      animation:
        - aid: 3
          time: 10
        - aid: 10003
          time: 10
